### ISSUE TITLE
Build fails with libidn2.so.0 - No such file or directory

### ISSUE THREAD

**Issue by trevorsandy** [archimg/archlinux#21]
Hi, Can you shed some light on why my archlinux image builds just fine for some time and then suddenly fails with the message `wget: error while loading shared libraries: libidn2.so.0: cannot open shared object file: No such file or directory` ?

This behaviour has happened before. On the last occurrence, I switched from ' base/archlinux:2017.07.01' to  'base/archlinux:2017.11.01' which addressed the abend behaviour but since the last 3 or so days, base/archlinux:2017.11.01 is now failing as described.

You can see the log trace [here](https://travis-ci.org/trevorsandy/lpub3d-ci/jobs/333785567).

I'm using Docker Compose on Travis-CI. Here is my compose .yml...

```
FROM base/archlinux:2017.11.01
LABEL maintainer "Trevor SANDY <trevor.sandy@gmail.com>"
RUN pacman -Syy --noconfirm 
# > CreateDockerImage_archlinux.log 2>&1
RUN pacman -S --noconfirm --needed git wget unzip ccache base-devel libidn2 
# >> CreateDockerImage_archlinux.log 2>&1
RUN pacman -S --noconfirm --needed qt5-base qt5-tools 
# >> CreateDockerImage_archlinux.log 2>&1
RUN pacman -S --noconfirm --needed sudo \
    && groupadd -r user -g 1000 \
    && useradd -u 1000 -r -g user -m -d /user -s /sbin/nologin -c "Build pkg user" user \
    && chmod 755 /user \
    && echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user
WORKDIR /user
USER user
VOLUME ["/buildpkg", "/user/pkgbuild/src/lpub3d_linux_3rdparty"]
CMD sudo chown -R user:user /user/pkgbuild/.* \
    && wget https://raw.githubusercontent.com/trevorsandy/lpub3d-ci/master/builds/linux/CreatePkg.sh \
    && export DOCKER=true \
    && chmod +x CreatePkg.sh \
    && ./CreatePkg.sh \
    && if test -d /buildpkg; then \
      sudo cp -f /user/pkgbuild/*.pkg.tar.xz /buildpkg/; \
      sudo cp -f /user/pkgbuild/src/*.log /buildpkg/; \
      sudo cp -f /user/*.log /buildpkg/; \
      sudo cp -f /*.log /buildpkg/; \
    fi
```

Cheers,

**Comment by bebehei** [comment]
You trapped into a typical ArchLinux problem here: **Never use `pacman -Sy <package>`**. Always use `-Syu` or only `-S`.

ArchLinux is a rolling distro and does not have a feature freeze every few months. So, if you `-Sy`, you download the latest index and then install the latest index. But in some cases, the dependencies of a package won't get updated. As there is no feature freeze, the API of the libraries and the API, which is required by the programs are subject to change all the time and therefore only updating some packages *may* lead to inconsitencies.

Let's look at a possible scenario, which triggers your problem: It can be the case, that a new `libidn` version gets released upstream. So when the `libidn` package will get distributed, the `wget` package will get rebuilt, too! So, your mirror will list only the new `libidn` and the new `wget` packages. When you install the `wget` package, the new version will get pulled, but the old `libidn` package is still there and your `wget` command links to the new `libidn` library file (which isn't there, because the old library is installed). `pacman` can't track, which version is compatible with which and therefore it can't stop and error or automatically upgrade `libidn`.

Therefore always `-Syu` and never `-Sy`.

---

```
FROM base/archlinux:2017.11.01
```

Ugh. No don't do this. It's an antipattern for ArchLinux systems.

You usually use tags to be able to rebuild your images a few years later and your `Dockerfile` still should build an image, which is quite similar to the one you've built today.

e.g: If you don't tag your `FROM ubuntu` images, you will likely have trouble in a few years to rebuild them, if some paths changed. Also the versions aren't the old ones. So: Always tag your `Ubuntu` images!

But it makes no sense on Arch. After a few months, the package index is out of date for almost every package. So you have to get the latest index anyways and install the latest packages and as I've outlined above, you have to use `-Syu` for this. But what does this until the end of the day? Your image will contain a full `base/archlinux:2017.11.01` image and also the full update of the package files. And at this point it makes more sense to have a full current image and a small update layer.

**Comment by trevorsandy** [comment]
Hi again, many thanks for your explanation. If using the FROM tag `base/archlinux:2017.11.01` is bad, can you share an example of a good Docker repo tag? It is not clear for me which tags are advisable to use in the Arch Docker repository.

So if I well understand your explanation, one should never use the Docker command `RUN pacman -Syy --noconfirm`, as I have, to build an Arch image? Instead, use `RUN pacman -Syu --noconfirm`. In my compose.yml file, I only used `pacman -S <package>`.

From reading your explanation, my thinking leads me to believe, using `-Syy` with a past snapshot (e.g. 2017.11.01) may lead to build failures because the index (as it is always using the latest lib versions) will be incompatible with the said past snapshot. Therefore, to combination of `-Syy` and a past snapshot is prone to fail at some point. The better approach being either use the latest image (in which case `-Syy` does not present a risk of the build failing), or use `-Syu` if it is not convenient to use the latest image. Is this thinking correct?

FYI, my workaround before reading your explanation was to simply add the libs which were reported missing. Using `FROM base/archlinux:2017.11.01`, I added the line `RUN pacman -S --noconfirm --needed libidn2 mpfr`.

Many thanks!

**Comment by bebehei** [comment]
> If using the FROM tag base/archlinux:2017.11.01 is bad, can you share an example of a good Docker repo tag? It is not clear for me which tags are advisable to use in the Arch Docker repository.

Simply use no tag or use latest. **You have to do a full system update anyways**. So it doesn't matter if you use latest or an old snapshot, which contains a full system update.

See here: https://gist.github.com/vodik/5660494

**Comment by bebehei** [comment]
https://wiki.archlinux.org/index.php?title=System_maintenance#Partial_upgrades_are_unsupported

**Comment by trevorsandy** [comment]
Excellent - thanks again. 

Perhaps it could be good to add a small note in base/archlinux - Full Description:

CAUTION: Keep in mind Arch Linux is a rolling release distribution. That means when new library versions are pushed to the repositories, all packages in the repositories that need to be rebuilt against those libraries are rebuilt. Therefore, it is imperative to use `RUN pacman -Syu [other flags]` if you are using tags other than latest `base/archlinux:latest` or last buld date `base/archlinux:YYYY.MM.DD`. See [partial upgrades are unsupported](https://wiki.archlinux.org/index.php?title=System_maintenance#Partial_upgrades_are_unsupported)  for full details.

Cheers,

**Comment by bebehei** [comment]
@trevorsandy I see your point. I've added a comment to the README.
